spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: saumya
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql

  graphql:
    graphiql:
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: pearlautherizer@gmail.com
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: my-super-secret-jwt-key-1234567890
  expiration: 604800000
